music/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "music"

urlpatterns = [
    # /music/
    path('', views.IndexView.as_view(), name="index"),

    # /music/register/
    path('register/', views.UserFormView.as_view(), name="register"),

    # /music/<pk>/
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),

    # /music/album/add/
    path('album/add/', views.AlbumCreate.as_view(), name="album_add"),

    # /music/album/2/
    path('album/<int:pk>/', views.AlbumUpdate.as_view(), name="album_update"),

    # /music/album/2/delete/
    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name="album_delete"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include("music.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django import forms
from django.urls.base import is_valid_path
from django.views import generic
from django.urls import reverse_lazy
from .models import Album, Song
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import UserForm

# Create your views here.


class IndexView(generic.ListView):
    template_name = "music/index.html"
    context_object_name = "all_albums"

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'
    context_object_name = 'album'


class AlbumCreate(generic.CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(generic.UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(generic.DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(generic.View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # display form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process from data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # cleaned (normilazed) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User objects

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:

                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %} Create an Album {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">
                <form action="" class="form-horizontal" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'music/style.css' %}">
    <title>{% block title %} {% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand new" href="{% url 'music:index' %}">Zhantai</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'music:index' %}">Albums</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'music:index' %}">Songs</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" role="search" method="GET" action="#">
                <div class="form-group">
                    <input class="form-control mr-sm-2" type="text" role="search" aria-label="Search" name="q" value="">
                </div>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'music:album_add' %}">Add Album</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'music:index' %}">Logout</a>
                </li>
            </ul>

        </div>
    </nav>

    {% block body %}
    {% endblock %}

</body>

</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">
    <br>

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                        <img src="{{ album.album_logo.url }}" class="img-responsive" width="270" height="270">
                        {% else %}
                        <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:index' %}">View All</a></li>
                <span> &nbsp;&nbsp;&nbsp;&nbsp;</span>
                <li role="presentation"><a href="#">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Audio File</th>
                                <th>Favorite</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite">
                                        {% if album.is_favorite %}
                                        <img src="https://image.flaticon.com/icons/png/512/1828/1828884.png" width="20"
                                            height="20">
                                        {% else %}
                                        <img src="https://image.flaticon.com/icons/png/512/1828/1828970.png" width="20"
                                            height="20">
                                        {% endif %}
                                    </a>
                                </td>
                                <td>
                                    <form action="#" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label for="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
</div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block title %} All Albums {% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <br>
            <h1>{{ user.username }}'s Albums</h1>
            <br>
        </div>
        {% if all_albums %}
        {% for album in all_albums %}
        <div class="col-sm-4 col-lg-4">
            <div class="thumbnail">
                <a href="{% url 'music:detail' album.id %}">
                    <img src="{{ album.album_logo.url }}" class="img-responsive" width="350" height="350">
                </a>
                <div class="caption">
                    <h2>{{ album.album_title }}</h2>
                    <h4>{{ album.artist }}</h4>

                    <!-- View Details -->
                    <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View
                        Details</a>

                    <!-- Delete Album -->
                    <form action="{% url 'music:album_delete' album.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="album_id" value="{{ album.id }}" />
                        <button type="submit" class="btn btn-default btn-sm delete">
                            <img src="https://image.flaticon.com/icons/png/512/1214/1214428.png" width="20" height="20">
                        </button>
                    </form>

                    <!-- Favorite Album -->
                    <a href="#" class="btn btn-default btn-sm btn-favorite">
                        {% if album.is_favorite %}
                        <img src="https://image.flaticon.com/icons/png/512/1828/1828884.png" width="20" height="20">
                        {% else %}
                        <img src="https://image.flaticon.com/icons/png/512/1828/1828970.png" width="20" height="20">
                        {% endif %}
                    </a>

                </div>
            </div>
        </div>

        {% endfor %}
        {% else %}
        <div class="col-sm-12">
            <br>
            <a href="{% url 'music:album_add' %}">
                <button type="button" class="btn btn-success">
                    Add an Album
                </button>
            </a>
        </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
    <div class="row">
        <div class="col-sm-12">
            <h3>Songs</h3>
        </div>
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in songs %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>{{ song.album.artist }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'music:detail' song.album.id %}">
                                        <img src="{{ song.album.album_logo }}" class="img-responsive"
                                            style="width: 20px; float: left; margin-right: 10px;" />
                                    </a>
                                    <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                </td>
                                <td>
                                    <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span
                                            class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

</div>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %} Register {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">
                <form action="" class="form-horizontal" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}